/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32f103c6.h"
#include "stm32f103c6_ISR_DRIVER.h"
#include "GPIO_DRIVER.h"

void v (){
	TogglePin(GPIOB, pin0);
	TogglePin(GPIOB, pin1);
	TogglePin(GPIOB, pin2);
	TogglePin(GPIOB, pin3);
	TogglePin(GPIOB, pin4);
	TogglePin(GPIOB, pin5);
	TogglePin(GPIOB, pin6);
	TogglePin(GPIOB, pin7);
	TogglePin(GPIOB, pin8);
	TogglePin(GPIOB, pin9);
	TogglePin(GPIOB, pin10);
}
int main(void)
{
	GPIOA_Clock_Enable();
	GPIOB_Clock_Enable();
	AFIO_Clock_Enable();
	pinmode(GPIOB, pin0,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin1,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin2,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin3,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin4,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin5,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin6,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin7,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin8,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin9,GPIO_MODE_OUTPUT_push_pull_Speed2);
	pinmode(GPIOB, pin10,GPIO_MODE_OUTPUT_push_pull_Speed2);

	EXTI(GPIOA,pin0,EXTI_Trigger_Rising, v);
	EXTI(GPIOA,pin2,EXTI_Trigger_Rising, v);
	EXTI(GPIOA,pin4,EXTI_Trigger_Rising, v);
	EXTI(GPIOA,pin6,EXTI_Trigger_Rising, v);
	EXTI(GPIOA,pin7,EXTI_Trigger_Rising, v);
	EXTI(GPIOA,pin10,EXTI_Trigger_Rising, v);

	for(;;);
}

