/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "EEPROM.h"

int main(void)
{
	unsigned char ch1[] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
		unsigned char ch2[7] = {0};

		eeprom_init();
		EEprom_write(0xAF, ch1, 7);
		EEprom_read(0xAF, ch2, 7);

	//test case2
		ch1[0] = 0xA;
		ch1[1] = 0xB;
		ch1[2] = 0xC;
		ch1[3] = 0xD;

		EEprom_write(0xFF, ch1, 4);
		EEprom_read(0xff, ch2, 4);




		while(1){


		}
}
