/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103c6_ADC.h"
#include "STM32_TIMERS_DRIVER.h"
#include "stm32f103c6_USART_SRIVER.h"
uint16_t X;
uint8_t text[5];
int main(void)
{
	ADC_INIT(ADC1, ADC_STATE_START);
	USART_INIT(USART1, mode_RX_TX_ENABLE, word_length_8, stop_bits_1, baud_rate_9600, parity_none,8000000);

	while(1){
		X=ADC_READ(ADC1, ADC_pin_PA1);
		sprintf(text,"%d",X);
		USART_SEND_STRING(USART1,text);
		delay(100, U_ms,8000000);
		USART_SEND_STRING(USART1,"\n");
		delay(100, U_ms,8000000);
	}
}
