/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stdint.h"
#define RCC_BASE   0x40021000
#define PORTA_BASE 0x40010800

#define RCC_APB2ENR *((volatile uint32_t*)(RCC_BASE+0x18))
#define CRH *((volatile uint32_t*)(PORTA_BASE+0x04))
#define ODR *((volatile uint32_t*)(PORTA_BASE+0x0C))

typedef union {
	volatile uint32_t all_bits ;
	struct {
		volatile uint32_t reserved :13;
		volatile uint32_t p13 :1;
	}pin;
}port;

int main(void)
{
	volatile port* portA =(volatile port*)(PORTA_BASE+0x0C);
	RCC_APB2ENR|=1<<2;
	CRH &=0xff0fffff;
	CRH |=0x00200000;

	while(1){
		portA->pin.p13=1;

		for(int i=0;i<=5000;i++);
		portA->pin.p13=0;

		for(int i=0;i<=5000;i++);
	}
	return 0;
}
