/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32f103c6.h"
#include "GPIO_DRIVER.h"

int main(void)
{
	GPIOA_Clock_Enable();
    pinmode(GPIOA, pin0,GPIO_MODE_INPUT_PD);
    pinmode(GPIOA, pin1,GPIO_MODE_OUTPUT_Open_drain_Speed2);
    pinmode(GPIOA, pin2,GPIO_MODE_ANALOG);
    pinmode(GPIOA, pin3,GPIO_MODE_OUTPUT_AF_Open_drain_Speed50);
    pinmode(GPIOA, pin4,GPIO_MODE_OUTPUT_Open_drain_Speed2);
    pinmode(GPIOA, pin5,GPIO_MODE_OUTPUT_Open_drain_Speed2);
    pinmode(GPIOA, pin6,GPIO_MODE_OUTPUT_Open_drain_Speed2);
    pinmode(GPIOA, pin7,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin8,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin9,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin10,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin11,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin12,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin13,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin14,GPIO_MODE_OUTPUT_push_pull_Speed10);
    pinmode(GPIOA, pin15,GPIO_MODE_OUTPUT_push_pull_Speed10);
   // pinmode(GPIOA, pin7,GPIO_MODE_OUTPUT_push_pull_Speed10);


  // WRITE_PORT(GPIOA,0xffff);
	while(1){
		if(READ_PIN(GPIOA, pin0)==1){
			pinwrite(GPIOA, pin7,HIGH);
		}
		else {
			pinwrite(GPIOA, pin7,LOW);
		}
	}
}
