/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32_I2C_LCD.h"
#include "STM32_TIMERS_DRIVER.h"
int i=0;
#define address 0x3f
int main(void)
{
	delay(200, U_ms,8000000);
	I2C_LCD_Init(I2C1,address);
	I2C_LCD_write_string(I2C1,"MOHAMMED",address);
	I2C_LCD_setcerser(I2C1, address,1,0);
	while(1){
		I2C_LCD_setcerser(I2C1, address,1,0);
		I2C_LCD_write_string(I2C1,"MOHAMMED ",address);
		I2C_LCD_write_INTnumber(I2C1, address,i);
		delay(300, U_ms,8000000);
		if(i<100)i++;
		else i--;
		I2C_LCD_clear( I2C1,address);
	}

}
