/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32f103c6.h"
#include "GPIO_DRIVER.h"
#include "LCD.h"
#include "keypad.h"
int main(void)
{

	GPIOA_Clock_Enable();
	//GPIOB_Clock_Enable();
	LCD_Init();
	Keypad_init();
	LCD_write_string("m");
		int i=10;

	    float f =10.5;
	    while (1)
	    {
			_delay_ms(100);
			LCD_write_data(Keypad_getkey());
			LCD_write_string(":moalshreif ");
			LCD_write_INTnumber(i);
			LCD_setcerser(1,0);
			LCD_write_FLOATnumber(f,6);
			LCD_write_string("m");
			_delay_ms(1000);
			LCD_clear();
			i--;
			f=f-.5f;

	    }
}
