

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103c6_ADC.h"
#include "STM32_TIMERS_DRIVER.h"
#include "stm32f103c6_USART_SRIVER.h"
#include "string.h"
#define clk 36000000
uint16_t X;
uint8_t text[5];

int main(void)
{
	MCAL_speed_init(CLK_SORC_IN_CLK8MHz,mood_FAST_MOOD_36MHzCORE);//speed of all 36MHz
	USART_INIT(USART3, mode_RX_TX_ENABLE, word_length_8, stop_bits_1, baud_rate_9600, parity_none,clk);
	ADC_INIT(ADC2, ADC_STATE_START);

	SPWM_SINGLE_PHASE_INIT(WAVE_NUMBER_6,10, clk);
	SPWM_WRITE(10, WAVE_NUMBER_6, clk);
	while (1)
	{
		X=200*ADC_READ(ADC2, ADC_pin_PA1)/4095+3;
		SPWM_WRITE(X, WAVE_NUMBER_10, clk);
		sprintf(text,"%d",X);
		USART_SEND_STRING(USART3,strcat(text," Hz \n"));
		delay(1000, U_ms,clk);
	}
}

