/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32_TIMERS_DRIVER.h"
#include "stm32_speed_DRIVER.h"
#include "GPIO_DRIVER.h"
int main(void)
{
	MCAL_speed_init(CLK_SORC_IN_CLK8MHz, mood_FAST_MOOD_72MHzCORE);//speed of all 36MHz
	//	PWM(TIM2, CH_1,50,5000,36000000);
	//	PWM(TIM2, CH_2,40,5000,36000000);
	//	PWM(TIM2, CH_3,20,5000,36000000);
	//	PWM(TIM2, CH_4,10,5000,36000000);
	GPIOA_Clock_Enable();
	pinmode(GPIOA, pin0, GPIO_MODE_OUTPUT_push_pull_Speed10);
	PWM(TIM3, CH_1,50,10,36000000);
	PWM(TIM3, CH_2,40,10,36000000);
	PWM(TIM3, CH_3,30,10,36000000);
	PWM(TIM3, CH_4,10,10,36000000);

	PWM(TIM1, CH_1,50,10,36000000);
	PWM(TIM1, CH_2,40,10,36000000);
	PWM(TIM1, CH_3,30,10,36000000);
	PWM(TIM1, CH_4,10,10,36000000);
	while(1){
		pinwrite(GPIOA, pin0,HIGH);
		delay(1000, U_ms,36000000);
		pinwrite(GPIOA, pin0,LOW);
		delay(1000, U_ms,36000000);
	}
}
